- name: executing remote ssh commands using ssh key
  uses: appleboy/ssh-action@v0.1.7
  with:
     host: ${{ secrets.SSH_HOST }}
     username: ${{ secrets.SSH_USERNAME }}
     key: ${{ secrets.SSH_KEY }}
     port: ${{ secrets.SSH_PORT }}
     script: whoami
