# .github/workflows/example-1.yml

name: ${GITHUB_REF_NAME}
on: [workflow_dispatch]
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: ...
        run: ...
